### ISSUE TITLE
EnergyBudget Widget Issues

### ISSUE THREAD

**Issue by philipoe** [ethz-asl/qgc_asl#3] opened 2015-06-19 17:15 UTC
This shall serve as a thread to collect energy budget widget errors:
- [x] The cell power is sometimes wrong. This is because the MPPT measurements for the current (on which the power calculations are based) only arrive when the MPPT is in continuous operating mode, which is not the case at low income power. The widget shall therefore add a mppt_timestamp variable, and if the last reception of an mppt message is > X seconds (2-3s seems appropriate), then the mppt_data shall beconsidered invalid. In this case, it is then enough to calculate the cell power using the ADC121 total power minus the current reported by the BATMONs. 

@ASM3 Please add the issues that you saw here.

**Comment by ASM3** [comment] 2015-06-20 18:46
- [x] Set the threshold at ~200mA (or better if possible a hysteresis) on the power animation for the CSPB sensor measurements (the problem is, that at the moment the power animation is switching all the time around zero)
- [x] Add/fix MPPT status messages (For CC/CV bit: 0 = CC 1 = CV)
- [x] Graphics label is black on black - not visible
- [x] Add MPPT combined current and power for better power overview

**Comment by oberion** [comment] 2015-07-06 08:29
- [x] Adapt the text color according to the selected stylesheet

**Comment by oberion** [comment] 2015-07-07 08:22
- [x] In the overview tab show the current instead of power

**Comment by philipoe** [comment] 2015-07-07 08:47
- [x] Add current throttle setting (e.g. "Throt: X%") to the graphics image next to the current system-level power consumption. This will help a lot to determine motor failures (which show low power, high throttle)

**Comment by oberion** [comment] 2015-07-07 15:21
- [x] Fix ya bug in the Graphics view. Power flow MPPT -> System is wrong

**Comment by oberion** [comment] 2015-09-21 15:31
Close this Issue for now. All the necessary changes should be in the master. For new issues feel free to reopen.

**Closed as completed by oberion** 2015-09-21 15:31 UTC
